entryPoints:
  web:
    address: :80
  websecure:
    address: :443

providers:
  file:
    filename: /etc/traefik/renderws.yml
    watch: true

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true
