version: "3.7"

services:
  traefik:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik.bare.yml:/etc/traefik/traefik.yml
      - ./renderws.yml:/etc/traefik/renderws.yml

  # Sites
  carltonwin8:
    image: nginx:1.19-alpine
    volumes:
      - ./sites/carltonwin8/web:/usr/share/nginx/html
