version: "3.7"

services:
  traefik:
    image: traefik:v2.3
    ports:
      - "80:80"
    volumes:
      - .:/etc/traefik

# Sites
  carltonwin8:
    image: nginx:v1.19-alpine
    volumes: 
      - ./sites/carltonwin8/web:/usr/share/nginx/html
 
# Test sites
  apiserver1:
    image: apiserver1
    ports:
      - "1111:1111"
    environment:
      - "PORT=1111"
  apiserver2:
    image: apiserver1
    ports:
      - "2222:2222"
    environment:
      - "PORT=2222"
  apiserver3:
    image: apiserver1
    ports:
      - "3333:3333"
    environment:
      - "PORT=3333"
  apiserver4:
    image: apiserver1
    ports:
      - "4444:4444"
    environment:
      - "PORT=4444"
