version: "3.7"

services:
  traefik:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`traefik`)"
        - "traefik.http.routers.api.entrypoints=web"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"

  # Sites
  tinaandcarlton:
    image: nginx:1.19-alpine
    volumes:
      - ./sites/tinaandcarlton/web:/usr/share/nginx/html
    deploy:
      labels:
        - "traefik.enable=true"
        # Router
        - "traefik.http.routers.tinaandcarlton.rule=Host(`tinaandcarlton`)"
        - "traefik.http.routers.tinaandcarlton.entrypoints=web"
        - "traefik.http.services.tinaandcarlton.loadbalancer.server.port=80"

  tinaandcarltonhawaii:
    image: apiserver1
    environment:
      - "PORT=1111"
    deploy:
      labels:
        - "traefik.enable=true"
        # Router
        - "traefik.http.routers.tinaandcarltonhawaii.rule=Host(`tinaandcarlton`) && Path(`/hawaii`)"
        - "traefik.http.routers.tinaandcarltonhawaii.entrypoints=web"
        - "traefik.http.services.tinaandcarltonhawaii.loadbalancer.server.port=1111"
