version: "3.7"

services:
  tinaandcarltonhawaii:
    image: hawaii
    volumes:
      - /renderws/carltonData/cj_pics/pics2020/hawaii:/carltonData/cj_pics/pics2020/hawaii
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.tinaandcarltonhawaii.loadbalancer.server.port=3000"
        - "traefik.http.routers.tinaandcarltonhawaii.entrypoints=web"
        - "traefik.http.routers.tinaandcarltonhawaii.rule=Host(`tinaandcarlton`) && Path(`/hawaii`)"
        - "traefik.http.routers.tinaandcarltonhawaii-secure.entrypoints=websecure"
        - "traefik.http.routers.tinaandcarltonhawaii-secure.rule=Host(`tinaandcarlton`) && Path(`/hawaii`)"
        - "traefik.http.routers.tinaandcarltonhawaii-secure.service=tinaandcarltonhawaii"
        - "traefik.http.routers.tinaandcarltonhawaii-secure.tls.certResolver=hawaii"
        #- "traefik.http.routers.tinaandcarltonhawaii-secure.tls.options=tlsoptions"
