entryPoints:
  web:
    address: :80
  websecure:
    address: :443

providers:
  docker:
    exposedByDefault: false
    swarmMode: true

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

tls:
  options:
    tlsoptions:
      minVersion: VersionTLS12
