http:
  routers:
    tinaandcarltonRouter:
      rule: "Host(`tinaandcarlton`)"
      service: tinaandcarlton
      entrypoints: web
    tinaandcarltonRouter-secure:
      rule: "Host(`tinaandcarlton`)"
      service: tinaandcarlton
      entrypoints: websecure
      tls: {}
    tinaandcarltonHawaiiRouter:
      rule: "Host(`tinaandcarlton`) && Path(`/hawaii`)"
      service: tinaandcarltonhawaii
      entrypoints: web

  services:
    tinaandcarlton:
      loadBalancer:
        servers:
          - url: "http://tinaandcarlton:80"
    tinaandcarltonhawaii:
      loadBalancer:
        servers:
          - url: "http://tinaandcarltonhawaii:1111"
